Harness IO Git Sync. MODIFY: Setup/Applications/My Application/Services/My Tomcat App/Commands/Start.yaml

diff --git a/Setup/Applications/My Application/Services/My Tomcat App/Commands/Start.yaml b/Setup/Applications/My Application/Services/My Tomcat App/Commands/Start.yaml
--- a/Setup/Applications/My Application/Services/My Tomcat App/Commands/Start.yaml
+++ b/Setup/Applications/My Application/Services/My Tomcat App/Commands/Start.yaml
@@ -4,8 +4,7 @@ commandUnits:
   - workingDirectory: $WINGS_RUNTIME_PATH/tomcat/bin
     command: ./startup.sh
     filePatternEntryList:
-      - filePath: $WINGS_RUNTIME_PATH/tomcat/logs/catalina.out
-        searchPattern: Server startup in
+      - {}
     name: Start Service
     commandUnitType: EXEC
     deploymentType: SSH
@@ -14,17 +13,17 @@ commandUnits:
         i=0
         while [ "$i" -lt 30 ]
         do
-            pgrep -f "\-Dcatalina.home=$WINGS_RUNTIME_PATH/tomcat"
-            rc=$?
-            if [ "$rc" -eq 0 ]
-            then
-                exit 0
-                sleep 1
-                i=$((i+1))
-            else
-                sleep 1
-                i=$((i+1))
-            fi
+                pgrep -f "\-Dcatalina.home=$WINGS_RUNTIME_PATH/tomcat"
+                rc=$?
+                if [ "$rc" -eq 0 ]
+                then
+                        exit 0
+                        sleep 1
+                        i=$((i+1))
+                else
+                        sleep 1
+                        i=$((i+1))
+                fi
         done
         exit 1
     name: Process Running
@@ -39,8 +38,8 @@ commandUnits:
         port=$(grep "<Connector[ ]*port=\"[0-9]*\"[ ]*protocol=\"HTTP/1.1\"" "$server_xml" |cut -d '"' -f2)
         nc -v -z -w 5 localhost $port
         else
-          echo "Tomcat config file("$server_xml") does not exist.. port check failed."
-          exit 1
+            echo "Tomcat config file("$server_xml") does not exist.. port check failed."
+            exit 1
         fi
     name: Port Listening
     commandUnitType: PORT_CHECK_LISTENING
